create database exmp1;
use exmp1;
create table STD (Stdname varchar(20) , rollno int not null, age int, branch varchar(20));
select * from STD;
insert into STD (Stdname, rollno, age, branch) values ( 'Abin', 1, 26, 'CSE');
insert into STD (Stdname, rollno, age, branch) values ( 'Melvin', 2, 25, 'CSE');
insert into STD (Stdname, rollno, age, branch) values ( 'Sam', 3, 23, 'EEE');
insert into STD (Studentname, rollno, age, branch) values ( 'Sidharth', 4, 22, 'Mec');
insert into STD (Studentname, rollno, age, branch) values ( 'Arun', 5, 21, 'ECE');
insert into STD (Studentname, rollno, age, branch, totalmark ) values ( 'Kevin', 6, 28, 'Civil',150);
alter table STD change stdname  Studentname varchar(50) primary key;
alter table STD add column totalmark int;
update STD set totalmark = 160 where Studentname = 'Abin';
update STD set totalmark = 155 where Studentname = 'Melvin';
update STD set totalmark = 123 where Studentname = 'Sam';
update STD set totalmark = 148 where Studentname = 'Sidharth';
update STD set totalmark = 133 where Studentname = 'Arun';
select * from STD where branch = 'CSE';
select * from STD where age<25;
select avg(totalmark) from STD;
select Studentname, rollno, totalmark from STD order by totalmark desc;
select Studentname, rollno, totalmark from STD where totalmark between 130 and 150;
select Studentname, rollno, totalmark from STD where totalmark not between 130 and 150;
update STD set totalmark = totalmark + 10;
select  max(totalmark) from STD;
select  min(totalmark) from STD;
select  sum(totalmark) from STD;
select * from STD where Studentname regexp "^Si";
select * from STD where Studentname regexp "un$";
select * from STD where Studentname like "%in";
select * from STD;
